# Generated by Django 5.1.4 on 2025-01-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
