# Generated by Django 5.1.4 on 2025-01-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_chatroom_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
