# Generated by Django 5.1.4 on 2025-01-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_alter_directmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='messageType',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directmessage',
            name='replyId',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
