# Generated by Django 5.1.4 on 2025-01-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_directmessage_messagetype_directmessage_replyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='messageType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='replyId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
