# Generated by Django 5.1.4 on 2025-01-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_alter_directmessage_messagetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='directmessage',
            old_name='messageType',
            new_name='message_type',
        ),
        migrations.RenameField(
            model_name='directmessage',
            old_name='sender',
            new_name='sentBy',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='replyId',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='createdAt',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directmessage',
            name='reaction',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directmessage',
            name='reply_message',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
