# Generated by Django 5.1.4 on 2025-01-31 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_rename_content_directmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temporarySent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
