# Generated by Django 5.1.4 on 2025-02-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_userprofile_temporarysent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='delivered', max_length=100),
        ),
    ]
