# Generated by Django 5.1.4 on 2025-02-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0010_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='status',
            field=models.CharField(default='delivered', max_length=100),
        ),
    ]
