# Generated by Django 5.1.4 on 2025-02-15 02:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0011_remove_userprofile_status_directmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hobbiesAndInterests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), default=list, size=None),
        ),
    ]
